product_routing:
    resource: "@DyweeProductBundle/Resources/config/routing/product.yml"

product_downloadable_routing:
    resource: "@DyweeProductBundle/Resources/config/routing/product_downloadable.yml"

product_pack_routing:
    resource: "@DyweeProductBundle/Resources/config/routing/product_pack.yml"

product_service_routing:
    resource: "@DyweeProductBundle/Resources/config/routing/product_service.yml"

product_subscription_routing:
    resource: "@DyweeProductBundle/Resources/config/routing/product_subscription.yml"

product_brand_routing:
    resource: "@DyweeProductBundle/Resources/config/routing/brand.yml"

product_categories_routing:
    resource: "@DyweeProductBundle/Resources/config/routing/category.yml"


base_product_dashboard:
    path:     /admin/product/dashboard
    defaults: { _controller: DyweeProductBundle:BaseProduct:dashboard }
