product_brand_table:
    path: /admin/product/brand/{page}
    defaults: {_controller: DyweeProductBundle:Brand:table, page: 1}
    requirements:
        page: \d*

product_brand_add:
    path: /admin/product/brand/add
    defaults: { _controller: DyweeProductBundle:Brand:add }

product_brand_update:
    path: /admin/product/brand/{id}/update
    defaults: { _controller: DyweeProductBundle:Brand:update }
    requirements:
        id: \d+

product_brand_delete:
    path: /admin/product/brand/{id}/delete
    defaults: { _controller: DyweeProductBundle:Brand:delete }
    requirements:
        id: \d+