product_category_table:
    path:     /admin/product/category/table/{page}
    defaults: { _controller: DyweeProductBundle:Category:table, page:1 }
    requirements:
        page: \d*

product_parentCategory_table:
    path:     /admin/product/category/{id}/{page}
    defaults: { _controller: DyweeProductBundle:Category:table, page:1 }
    requirements:
        page: \d*
        id: \d*

product_category_add:
    path:     /admin/product/category/add
    defaults: { _controller: DyweeProductBundle:Category:add }

product_category_update:
    path:     /admin/product/category/{id}/update
    defaults: { _controller: DyweeProductBundle:Category:update }
    requirements:
        id: \d+

product_category_delete:
    path:     /admin/product/category/{id}/delete
    defaults: { _controller: DyweeProductBundle:Category:delete }
    requirements:
        id: \d+

product_category_view:
    path:     /eshop/category/{data}
    defaults: { _controller: DyweeProductBundle:Category:view }

product_category_filterAjax:
    path:     /eshop/categoryFilter
    defaults: { _controller: DyweeProductBundle:Category:filterAjax }
    requirements:
        _methods: POST

product_category_view_brandFilter:
    path:     /eshop/category/{data}/{category}
    defaults: { _controller: DyweeProductBundle:Category:viewByBrand }