###############################
#                             #
#         NORMAL WAY          #
#                             #
###############################

product_view:
    path:     /product/{id}
    defaults: { _controller: DyweeProductBundle:Product:view, page:1 }
    requirements:
        page: \d*

product_table:
    path:     /admin/product
    defaults: { _controller: DyweeProductBundle:Product:table }

product_add:
    path:     /admin/product/add
    defaults: { _controller: DyweeProductBundle:Product:add }

product_adminView:
    path:     /admin/product/{id}
    defaults: { _controller: DyweeProductBundle:Product:adminView }
    requirements:
        id: \d*

product_update:
    path:     /admin/product/{id}/update
    defaults: { _controller: DyweeProductBundle:Product:update }
    requirements:
        id: \d*

product_delete:
    path:     /admin/product/{id}/delete
    defaults: { _controller: DyweeProductBundle:Product:delete }
    requirements:
        id: \d*



###############################
#                             #
#             REST            #
#                             #
###############################

#product_view:
#    path:     /rest/product/{id}
#    defaults: { _controller: DyweeProductBundle:RestProduct:table, page:1 }
#    requirements:
#        page: \d*


#product_add:
#    path:     /admin/rest/product/{id}
#    defaults: { _controller: DyweeProductBundle:RestProduct:table, page:1 }
#    requirements:
#        page: \d*


#product_adminView:
#    path:     /admin/rest/product/{id}
#    defaults: { _controller: DyweeProductBundle:RestProduct:table, page:1 }
#    requirements:
#        page: \d*

#product_update:
#    path:     /admin/product/{id}
#    defaults: { _controller: DyweeProductBundle:RestProduct:table, page:1 }
#    requirements:
#        page: \d*

#product_delete:
#    path:     /admin/product/{id}
#    defaults: { _controller: DyweeProductBundle:RestProduct:table, page:1 }
#    requirements:
#        page: \d*