###############################
#                             #
#         NORMAL WAY          #
#                             #
###############################

product_subscription_table:
    path:     /admin/product/subscription
    defaults: { _controller: Dywee\ProductBundle\Controller\ProductSubscriptionController::tableAction }

product_subscription_add:
    path:     /admin/product/subscription/add
    defaults: { _controller: Dywee\ProductBundle\Controller\ProductSubscriptionController::addAction }