###############################
#                             #
#         NORMAL WAY          #
#                             #
###############################

product_pack_table:
    path:     /admin/product/pack
    defaults: { _controller: DyweeProductBundle:ProductPack:table }

product_pack_add:
    path:     /admin/product/pack/add
    defaults: { _controller: DyweeProductBundle:ProductPack:add }