###############################
#                             #
#         NORMAL WAY          #
#                             #
###############################

product_pack_table:
    path:     /admin/product/pack
    defaults: { _controller: Dywee\ProductBundle\Controller\ProductPackController::tableAction }

product_pack_add:
    path:     /admin/product/pack/add
    defaults: { _controller: Dywee\ProductBundle\Controller\ProductPackController::addAction }