###############################
#                             #
#         NORMAL WAY          #
#                             #
###############################

product_downloadable_table:
    path:     /admin/product/downlodable
    defaults: { _controller: DyweeProductBundle:ProductDownloadable:table }

product_downloadable_add:
    path:     /admin/product/downlodable/add
    defaults: { _controller: DyweeProductBundle:ProductDownloadable:add }