###############################
#                             #
#         NORMAL WAY          #
#                             #
###############################

product_service_table:
    path:     /admin/product/service
    defaults: { _controller: DyweeProductBundle:ProductService:table }

product_service_add:
    path:     /admin/product/service/add
    defaults: { _controller: DyweeProductBundle:ProductService:add }