product_table:
    path:     /admin/product
    defaults: { _controller: Dywee\ProductBundle\Controller\ProductController::tableAction }

product_add:
    path:     /admin/product/add
    defaults: { _controller: Dywee\ProductBundle\Controller\ProductController::addAction }

product_view:
    path:     /admin/product/{id}
    defaults: { _controller: Dywee\ProductBundle\Controller\ProductController::adminViewAction }
    requirements:
        id: \d*

product_update:
    path:     /admin/product/{id}/update
    defaults: { _controller: Dywee\ProductBundle\Controller\ProductController::updateAction }
    requirements:
        id: \d*

product_delete:
    path:     /admin/product/{id}/delete
    defaults: { _controller: Dywee\ProductBundle\Controller\ProductController::deleteAction }
    requirements:
        id: \d*