###############################
#                             #
#         NORMAL WAY          #
#                             #
###############################

product_subscription_table:
    path:     /admin6833/product/subscription
    defaults: { _controller: DyweeProductBundle:ProductSubscription:table }

product_subscription_add:
    path:     /admin6833/product/subscription/add
    defaults: { _controller: DyweeProductBundle:ProductSubscription:add }